# POST http://localhost:3000/auth/signUp
# Content-Type: application/json

# {
#     "username": "niti@gmail.com",
#     "role": "1",
#     "name": "Niti",
#     "phone": "1234567890",
#     "password": "Niti1234567890"
# }


# POST http://localhost:3000/auth/login
# Content-Type: application/json

# {
#     "username": "niti@gmail.com",
#     "password": "Niti1234567890"
# }

# GET http://localhost:3000/users/getProfile/niti@gmail.com
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5pdGlAZ21haWwuY29tIiwiaWF0IjoxNjgxNTUyMTMyfQ.FRbmDVxMl7TzBeg6fYWfm9hsL3tT8wzgWXyL90ilQ5c