# POST http://localhost:3000/auth/signUp
# Content-Type: application/json

# {
#     "username": "hello@gmail.com",
#     "role": "1",
#     "name": "hello",
#     "phone": "1234",
#     "password": "1234"
# }


# POST http://localhost:3000/auth/login
# Content-Type: application/json

# {
#     "username": "jatin@gmail.com",
#     "password": "1234"
# }

# GET https://canteenmanagementserver.onrender.com/orders/getOrders/
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphdGluQGdtYWlsLmNvbSIsImlhdCI6MTY4MjM2MzAzM30.Hv34kzvxQwFzueUL1HHHsxzHmvjOh0Sx365z1m9-_g4


# PUT http://localhost:3000/users/updateName/
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxvQGdtYWlsLmNvbSIsImlhdCI6MTY4MjI0Njc1OH0.SsVXBoYqlM9AjAem-xz5JMuag5Woj2ECQ3xLvwefNbU

# {
#     "name": "helloagain"
# }

# POST http://localhost:3000/auth/resetPassword
# Content-Type: application/json

# {
#     "username": "test@gmail.com",
#     "password": "qwerty"
# }

# POST http://localhost:3000/auth/mailOTP
# Content-Type: application/json

# {
#     "username": "inayatk.grewal@gmail.com"
# }

# POST https://canteenmanagementserver.onrender.com/auth/login
# Content-Type: application/json

# {
#     "username": "test@gmail.com",
#     "password": "qwerty12"
# }

# GET https://canteenmanagementserver.onrender.com/cart/getMyCart/
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNjgyNTI3NjAxfQ.rsZa27VPOD1cndKkjVdZg1sWG7Dzns6Hs_FS_1xiN2M
